-- Version(version 1.0.0 ,初始化表格脚本)
DROP TABLE IF EXISTS CLUB_USER;
CREATE TABLE CLUB_USER (
    ACCOUNT VARCHAR(50) COMMENT "用户账号",
    USER_NAME VARCHAR(255) COMMENT "用户名称",
    PASSWORD VARCHAR(255) COMMENT "用户密码",
	DESCRIPTER VARCHAR(700),
    GENDER NUMERIC DEFAULT 0 COMMENT "性别2 女，1男，0保密，3第三",
    EMAIL VARCHAR(200) COMMENT "用户邮箱",
    AVATAR VARCHAR(1000) COMMENT "用户头像",
    LEVELES NUMERIC DEFAULT 1 COMMENT "权限等级",
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "记录时间",
    UPDATE_USER_ID VARCHAR(50) COMMENT "更新者id",
    UPDATE_USER_NAME VARCHAR(50) COMMENT "更新者",
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "更新时间"
);
ALTER TABLE CLUB_USER COMMENT '用户信息记录表';
ALTER TABLE CLUB_USER ADD CONSTRAINT ACCOUNT PRIMARY KEY (ACCOUNT);
CREATE INDEX USER_USER_NAME ON CLUB_USER (USER_NAME);
CREATE INDEX USER_EMAIL ON CLUB_USER (EMAIL);
CREATE INDEX USER_PASSWORD ON CLUB_USER (PASSWORD);
DROP TABLE IF EXISTS CLUB_NOTICE;
CREATE TABLE CLUB_NOTICE (
    UUID VARCHAR(50),
	DESCRIPTER VARCHAR(700),
    MODE NUMERIC DEFAULT 0,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "创建时间",
    UPDATE_USER_ID VARCHAR(50) COMMENT "更新者id",
    UPDATE_USER_NAME VARCHAR(50) COMMENT "更新者",
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "更新时间"
);
ALTER TABLE CLUB_NOTICE COMMENT '公告记录表';
ALTER TABLE CLUB_NOTICE ADD CONSTRAINT UUID PRIMARY KEY (UUID);
CREATE INDEX NOTICE_USER ON CLUB_NOTICE (UPDATE_USER_NAME);
CREATE INDEX NOTICE ON CLUB_NOTICE (DESCRIPTER);
DROP TABLE IF EXISTS CLUB_DISCUSS;
CREATE TABLE CLUB_DISCUSS (
    UUID VARCHAR(50),
	DESCRIPTER VARCHAR(700),
	NICKNAME VARCHAR(100),
    SCORE NUMERIC DEFAULT 0,
    MODE NUMERIC DEFAULT 0,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "创建时间",
    UPDATE_USER_ID VARCHAR(50) COMMENT "更新者id",
    UPDATE_USER_NAME VARCHAR(50) COMMENT "更新者",
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "更新时间"
);
ALTER TABLE CLUB_DISCUSS COMMENT '留言板记录表';
ALTER TABLE CLUB_DISCUSS ADD CONSTRAINT UUID PRIMARY KEY (UUID);
CREATE INDEX DISCUSS_USER ON CLUB_DISCUSS (UPDATE_USER_NAME);
CREATE INDEX DISCUSS ON CLUB_DISCUSS (DESCRIPTER);
DROP TABLE IF EXISTS BASE_GENERATOR_ID;
CREATE TABLE BASE_GENERATOR_ID (
    NAME VARCHAR(300) COMMENT "资源类型一般是类全名",
    CURVAL NUMERIC COMMENT "值"
);
ALTER TABLE BASE_GENERATOR_ID COMMENT 'GENERATOR_ID记录表';
ALTER TABLE BASE_GENERATOR_ID ADD CONSTRAINT NAME PRIMARY KEY (NAME);
DROP TABLE IF EXISTS CLUB_CONTENT;
CREATE TABLE CLUB_CONTENT (
    CODE VARCHAR(50),
	POSITON VARCHAR(700),
	DESCRIPTER VARCHAR(700),
    PRICE NUMERIC DEFAULT 0,
    MODE NUMERIC DEFAULT 0,
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "创建时间",
    UPDATE_USER_ID VARCHAR(50) COMMENT "更新者id",
    UPDATE_USER_NAME VARCHAR(50) COMMENT "更新者",
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "更新时间"
);
ALTER TABLE CLUB_CONTENT COMMENT '场地/器材记录表';
ALTER TABLE CLUB_CONTENT ADD CONSTRAINT CODE PRIMARY KEY (CODE,MODE);
CREATE INDEX CONTENT_POS ON CLUB_CONTENT (POSITON);
CREATE INDEX CONTENT_USER ON CLUB_CONTENT (UPDATE_USER_NAME);
CREATE INDEX CONTENT ON CLUB_CONTENT (DESCRIPTER);
DROP TABLE IF EXISTS CLUB_ORDER;
CREATE TABLE CLUB_ORDER (
    UUID VARCHAR(50),
    CODE VARCHAR(50),
    MODE NUMERIC DEFAULT 0,
    ENTRY NUMERIC DEFAULT 0,
	DESCRIPTER VARCHAR(700),
    CONTACT VARCHAR(50) COMMENT "使用者电话",
    USE_INFO VARCHAR(50) COMMENT "使用者信息",
    START_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "开始时间",
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "创建时间",
    UPDATE_USER_ID VARCHAR(50) COMMENT "更新者id",
    UPDATE_USER_NAME VARCHAR(50) COMMENT "更新者",
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "更新时间"
);
ALTER TABLE CLUB_ORDER COMMENT '订单记录表';
ALTER TABLE CLUB_ORDER ADD CONSTRAINT CODE PRIMARY KEY (UUID,CODE,MODE);
CREATE INDEX ORD_CODE ON CLUB_ORDER (CODE);
CREATE INDEX ORD_USER ON CLUB_ORDER (UPDATE_USER_NAME);
CREATE INDEX ORD_CONT ON CLUB_ORDER (CONTACT);
CREATE INDEX ORD_INFO ON CLUB_ORDER (USE_INFO);
CREATE INDEX ORD ON CLUB_ORDER (DESCRIPTER);
DROP TABLE IF EXISTS CLUB_ORDER_HIS;
CREATE TABLE CLUB_ORDER_HIS (
    UUID VARCHAR(50),
    CODE VARCHAR(50),
    MODE NUMERIC DEFAULT 0,
    ENTRY NUMERIC DEFAULT 0,
    RESULT NUMERIC DEFAULT 0,
    HOURS NUMERIC DEFAULT 0,
    PRICE NUMERIC DEFAULT 0,
	DESCRIPTER VARCHAR(700),
    CONTACT VARCHAR(50) COMMENT "使用者电话",
    USE_INFO VARCHAR(50) COMMENT "使用者信息",
    START_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "开始时间",
    FINISH_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "结束时间",
    CREATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "创建时间",
    UPDATE_USER_ID VARCHAR(50) COMMENT "更新者id",
    UPDATE_USER_NAME VARCHAR(50) COMMENT "更新者",
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "更新时间"
);
ALTER TABLE CLUB_ORDER_HIS COMMENT '订单历史记录表';
ALTER TABLE CLUB_ORDER_HIS ADD CONSTRAINT CODE PRIMARY KEY (UUID,CODE,MODE);
CREATE INDEX HIS_CODE ON CLUB_ORDER_HIS (CODE);
CREATE INDEX HIS_USER ON CLUB_ORDER_HIS (UPDATE_USER_NAME);
CREATE INDEX HIS_CONT ON CLUB_ORDER_HIS (CONTACT);
CREATE INDEX HIS_INFO ON CLUB_ORDER_HIS (USE_INFO);
CREATE INDEX HIS ON CLUB_ORDER_HIS (DESCRIPTER);
-- Version(version 1.0.1 ,登录日志)
DROP TABLE IF EXISTS CLUB_USER_LOGIN_LOG;
CREATE TABLE CLUB_USER_LOGIN_LOG (
    ACCOUNT VARCHAR(50) COMMENT "用户账号",
    UUID VARCHAR(50) COMMENT "用户名称",
    QUITER NUMERIC,
    FINISH_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "记录时间",
    START_TIME TIMESTAMP NULL DEFAULT NULL COMMENT "时间"
);
ALTER TABLE CLUB_USER_LOGIN_LOG COMMENT '用户登录日志信息记录表';
ALTER TABLE CLUB_USER_LOGIN_LOG ADD CONSTRAINT UUID PRIMARY KEY (UUID);
CREATE INDEX LOG_ACCOUNT ON CLUB_USER_LOGIN_LOG (ACCOUNT);
